languageCode = "en-us"
title = "Hugo Tailwind Starter"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "sitemap"]

navigateToChanged = true
metaDataFormat = "yaml"
enableEmoji = true

[context.production.environment]
  HUGO_VERSION = "0.55"

[blackfriday]
  hrefTargetBlank = true