languageCode = "en-us"
title = "Hugo Tailwind Starter"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "sitemap"]
metaDataFormat = "yaml"
enableRobotsTXT =  true

[context.production.environment]
  HUGO_VERSION = "0.55"

[blackfriday]
  hrefTargetBlank = true
